### ISSUE TITLE
 When will laravel9 be supported 

### ISSUE THREAD

**Issue by flyinglb** [ckfinder/ckfinder-laravel-package#81] opened 2022-04-18 07:35 UTC
When will laravel9 be supported.

**Comment by presleyd** [comment] 2022-05-03 19:19
Duplicate of #72

**Comment by zaak** [comment] 2022-11-17 08:29
Support for Laravel 9 has been added in the latest version. Please update `ckfinder/ckfinder-laravel-package`.

**Closed by zaak** 2022-11-17 08:29 UTC
