### ISSUE TITLE
Laravel 9 support!

### ISSUE THREAD

**Issue by cappie15** [ckfinder/ckfinder-laravel-package#83] opened 2022-04-21 07:21 UTC

**Comment by presleyd** [comment] 2022-05-03 19:19
Duplicate of #72

**Comment by tamedevelopers** [comment] 2022-10-20 14:19
Hello all. 

Laravel 9 refused CKFinder due to some version of Laravel issue on v9.

Problem 1
    - ckfinder/ckfinder-laravel-package v3.5.1 requires laravel/framework ^5.5 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^9.3.8).
    - ckfinder/ckfinder-laravel-package[v3.5.1.1, ..., v3.5.1.2] require laravel/framework ^5.5|~6.0 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^9.3.8).
    - ckfinder/ckfinder-laravel-package[v3.5.1.3, ..., v3.5.1.5] require laravel/framework ^5.5|~6.0|~7.0 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^9.3.8).
    - ckfinder/ckfinder-laravel-package[v3.5.1.6, ..., v3.5.2.1] require laravel/framework ^5.5|^6.0|^7.0|^8.0 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.3.8).
    - ckfinder/ckfinder-laravel-package v3.5.3 requires laravel/framework ^5.5|^6.20.42|^7.0|^8.0 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.20.42, v6.20.43, v6.20.44, 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.3.8).
    - Root composer.json requires ckfinder/ckfinder-laravel-package ^3.5 -> satisfiable by ckfinder/ckfinder-laravel-package[v3.5.1, ..., v3.5.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require ckfinder/ckfinder-laravel-package:*" to figure out 
if any version is installable, or "composer require ckfinder/ckfinder-laravel-package:^2.1" if you know which you need.

**Comment by zaak** [comment] 2022-11-17 08:29
Support for Laravel 9 has been added in the latest version. Please update `ckfinder/ckfinder-laravel-package`.

**Closed by zaak** 2022-11-17 08:29 UTC
